import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Sidebar from '../components/Sidebar'

export default function Home(data) {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to my first Next.js app
        </h1>

        <p>This is the homepage</p>
        <p>I'm using this to try the fun things I'm learning doing Next.js training.</p>
      </main>
      <Sidebar posts={data} />
    </div>
  )
}

export async function getServerSideProps() {
  // Fetch data from external API
  const res = await fetch(`https://jsonplaceholder.typicode.com/posts/`)
  const data = await res.json()

  // Pass data to the page via props
  return { props: { data } }
}
