import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Link from 'next/link'

export default function Posts({posts}) {
    console.log({posts})
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main className={styles.main}>
        <h1 className={styles.title}>
          List of Spells
        </h1>

        <div className='postsList'>

        <ul>
        {posts.map((post, index) => (
            <li key={index}>
                <Link as={`/post/${post.id}`} href="post/[id]">
                    <a>{post.name}</a>
                </Link>
            </li>
        ))}
        </ul>

        </div>
      </main>
    </div>
  )
}

// This function gets called at build time on server-side.
// It won't be called on client-side, so you can even do
// direct database queries.
export async function getStaticProps() {
  // Call an external API endpoint to get posts.
  // You can use any data fetching library
  const res = await fetch('https://wizard-world-api.herokuapp.com/Spells')
  const posts = await res.json()

  // By returning { props: { posts } }, the Blog component
  // will receive `posts` as a prop at build time
  return {
    props: {
      posts,
    },
  }
}
