import Header from "../../../components/Header"
import Head from 'next/head'

export default function Post({ post }) {
  return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <h1>
                    This is the posts page
                </h1>

                <div className="post">
                    <h1>{post.title.rendered}</h1>
                    {post.excerpt.rendered}
                </div>
                <a href={post.link}>Read Full Post</a>
            </main>
        </>

  )
}

// Get a list of all the blog posts...
export async function getStaticPaths() {

  // Call an external API endpoint to get posts.
  const res = await fetch('https://webdevstudios.com/wp-json/wp/v2/posts')

  // Turn the response into JSON.
  const posts = await res.json()

  // Get the paths we want to pre-render based on posts.
  const paths = posts.map((post) => ({
    params: {
      id: post.id.toString()
    }
  }))

  // Return a list of blog posts.
  return {
    paths,
    fallback: false // Means other routes should 404.
  }
}
// Query a single blog post...
export async function getStaticProps({ params }) {

  // Query blog post, based on `params.id`, generated from getStaticPaths()
  const res = await fetch(`https://webdevstudios.com/wp-json/wp/v2/posts/${params.id}`)

  // Turn the response into JSON.
  const post = await res.json()

  // Pass data to the <Post /> component.
  return {
    props: { post }
  }
}
