import Header from "../../../components/Header"
import Head from 'next/head'

export default function Post({ post }) {
  return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />

            <main>
                <div className="post">
                    <h1>Name: {post.name}</h1>
                    <h2>Incantation: {post.incantation}</h2>
                    <p>Effect: {post.effect}</p>
                </div>
            </main>
        </>

  )
}

// Get a list of all the blog posts...
export async function getStaticPaths() {

  // Call an external API endpoint to get posts.
  const res = await fetch('https://wizard-world-api.herokuapp.com/Spells')

  // Turn the response into JSON.
  const posts = await res.json()

  // Get the paths we want to pre-render based on posts.
  const paths = posts.map((post) => ({
    params: {
      id: post.id.toString()
    }
  }))

  // Return a list of blog posts.
  return {
    paths,
    fallback: false // Means other routes should 404.
  }
}
// Query a single blog post...
export async function getStaticProps({ params }) {

  // Query blog post, based on `params.id`, generated from getStaticPaths()
  const res = await fetch(`https://wizard-world-api.herokuapp.com/Spells/${params.id}`)

  // Turn the response into JSON.
  const post = await res.json()

  // Pass data to the <Post /> component.
  return {
    props: { post }
  }
}
